upd del error  build-and-deploy
src/pages/MovieDetails/MovieDetails.jsx
  Line 38:9:  'navigate' is assigned a value but never used  no-unused-vars

Error: Process completed with exit code 1.