fix   useEffect -
Errror Build Deploy
src/pages/MovieDetails/MovieDetails.jsx
  Line 23:6:  React Hook useEffect has a missing dependency: 'dataMovie'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

Error: Process completed with exit code 1.
===================== VSCode
WARNING in src\pages\MovieDetails\MovieDetails.jsx
  Line 23:6:  React Hook useEffect has a missing dependency: 'dataMovie'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

webpack compiled with 1 warning