upd del error build-and-deploy
src/pages/MovieDetails/MovieDetails.jsx
  Line 2:23:  'useNavigate' is defined but never used  no-unused-vars
Error: Process completed with exit code 1.